#!/bin/bash

PIDFILE=/var/run/bridge.pid

case $1 in
    start)
        python /home/pi/Bridge/main.py 2>/dev/null &
        echo $! > ${PIDFILE}
    ;;
    stop)
        kill `cat ${PIDFILE}`
        rm ${PIDFILE}
    ;;
    *)
        echo "usage: bridge {start|stop}" ;;
esac
exit 0
